Fix #12: configure detects either make or gmake

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -32,6 +32,7 @@ Optional features:
 Some influential environment variables:
   CC                      C compiler command [detected]
   AWK                     AWK tool command [detected]
+  MAKE                    gmake tool command [detected]
   AR                      archive command [detected]
   RANLIB                  ranlib archive indexer command [detected]
   CFLAGS                  C compiler flags [-Os -pipe ...]
@@ -59,6 +60,21 @@ trycc () { test -z "$CC" && cmdexists "$1" && CC=$1 ; }
 tryar () { test -z "$AR" && cmdexists "$1" && AR=$1 ; }
 tryranlib () { test -z "$RANLIB" && cmdexists "$1" && RANLIB=$1 ; }
 tryawk () { test -z "$AWK" && "$1" 'function works () {return 0} BEGIN{exit works()}' && AWK=$1 ; }
+trymake() {
+    if test -z "$MAKE" && cmdexists "$1" ; then
+	v=`$1 --version | grep 'GNU Make' | sed -e 's/.*Make //'`
+	if [ "$v" = "" ] ; then
+	    printf "Found but not using non-GNU make ($1)... "
+	else
+	    MAKE="$1"
+	    maj=`echo $v | cut -d. -f 1`
+	    min=`echo $v | cut -d. -f 2`
+	    if ! test $maj -gt 3 -o '(' $maj -eq 3 -a $min -ge 81 ')' ; then
+		printf "Warning: using make, but version $v < 3.81 has not been tested. "
+	    fi
+	fi
+    fi
+}
 
 stripdir () {
 while eval "fnmatch '*/' \"\${$1}\"" ; do eval "$1=\${$1%/}" ; done
@@ -303,6 +319,14 @@ printf "%s\n" "$AWK"
 test -n "$AWK" || fail "$0: cannot find an AWK tool"
 
 #
+# Find a MAKE tool to use#
+
+printf "checking for MAKE tool... "
+for a in make gmake ; do trymake "$a"; done
+printf "%s\n" "$MAKE"
+test -n "$MAKE" || fail "$0: cannot find a MAKE tool"
+
+#
 # Find a C compiler to use
 #
 printf "checking for C compiler... "
@@ -503,6 +527,8 @@ MANPREFIX = $MANDIR
 SHAREPREFIX = $SHAREDIR
 CC = $CC
 AWK = $AWK
+MAKE = $MAKE
+
 AR = $AR
 RANLIB = $RANLIB
 CFLAGS = $CFLAGS
@@ -540,5 +566,18 @@ exec 1>&3 3>&-
 # cp -p $CONFIGFILE app/ext_example/
 
 printf "done\n"
+
+if ! [ "$MAKE" = "" ]; then
+   echo ""
+   echo "To build and install, run"
+   echo "  $MAKE install"
+   echo ""
+   echo "Other common commands:"
+   echo "  (cd src && $MAKE install)"
+   echo "  (cd app && $MAKE install)"
+   echo "  $MAKE uninstall"
+   echo "  $MAKE clean"
+   echo ""
+fi
 
 exit 0
