463-pcre8-build (#464)
* add regex + F tests
* add --pcre2-8-prefix=builtin default to build pcre2 library from included source
* update third-party licenses and add link from README

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -19,8 +19,10 @@ Optional configuration:
   --jq-prefix=JQ_PREFIX   specify directory containing lib/libjq and include/jq.h
                           defaults to PREFIX if not specified and PREFIX/include/jq.h exists
   --pcre2-8-prefix=PCRE2_8_PREFIX
-                          specify directory containing lib/libpcre2-8 and include/pcre2-8.h
-                          defaults to PREFIX if not specified and PREFIX/include/pcre2.h exists
+                          no=do not use pcre2
+                          builtin=build from included source (pcre2-10.47)
+                          otherwise, specify dir with lib/libpcre2-8 and include/pcre2-8.h
+                          defaults to 'builtin' if not specified
 
 Installation directories:
   --prefix=PREFIX         main installation prefix [\$PREFIX or /usr/local]
@@ -751,18 +753,25 @@ else
 fi
 
 HAVE_PCRE2_8=
-if [ "$PCRE2_8_PREFIX" = "" ] && [ "$PREFIX" != "" ] && [ -f "$PREFIX/include/pcre2.h" ] ; then
-    PCRE2_8_PREFIX="$PREFIX"
+if [ "$PCRE2_8_PREFIX" = "" ] ; then
+    PCRE2_8_PREFIX=builtin
 fi
+if [ "$PCRE2_8_PREFIX" = "builtin" ] ; then
+    HAVE_PCRE2_8=1
+else
+    if [ "$PCRE2_8_PREFIX" = "" ] && [ "$PREFIX" != "" ] && [ -f "$PREFIX/include/pcre2.h" ] ; then
+        PCRE2_8_PREFIX="$PREFIX"
+    fi
 
-if [ "$PCRE2_8_PREFIX" != "" ] && [ "$CROSS_COMPILING" = "no" ] ; then
-    printf "checking --pcre2-8-prefix ${PCRE2_8_PREFIX} ... "
-    if ! tryldflag LDFLAGS_PCRE2_8 -lpcre-8 -L"$PCRE2_8_PREFIX"/lib ; then
-        echo "Error: Failed to compile with -lpcre2-8 and -L$PCRE2_8_PREFIX/lib"
-    else
-        HAVE_PCRE2_8=1
-        if [ "$PCRE2_8_PREFIX" != "$PREFIX" ]; then
-            LDFLAGS_PCRE2_8="$LDFLAGS_PCRE2_8 -L$PCRE2_8_PREFIX/lib"
+    if [ "$PCRE2_8_PREFIX" != "no " ] ; then
+        if [ "$PCRE2_8_PREFIX" != "" ] && [ "$CROSS_COMPILING" = "no" ] ; then
+            # TO DO: check for pcre2 static lib
+            printf "checking --pcre2-8-prefix ${PCRE2_8_PREFIX} ... "
+            if ! tryldflag LDFLAGS_PCRE2_8 -lpcre2-8 -L"$PCRE2_8_PREFIX"/lib ; then
+                echo "Error: Failed to compile with -lpcre2-8 and -L$PCRE2_8_PREFIX/lib"
+            else
+                HAVE_PCRE2_8=1
+            fi
         fi
     fi
 fi
@@ -821,7 +830,6 @@ LDFLAGS_JQ = $LDFLAGS_JQ
 
 HAVE_PCRE2_8 = $HAVE_PCRE2_8
 PCRE2_8_PREFIX = $PCRE2_8_PREFIX
-LDFLAGS_PCRE2_8 = $LDFLAGS_PCRE2_8
 
 STATIC_LIBS = $STATIC_LIBS
 CFLAGS_AUTO = $CFLAGS_AUTO
@@ -866,55 +874,55 @@ exec 1>&3 3>&-
 printf "done\n"
 
 echo ""
-echo "****************************************************************"
-echo "*  zsv configuration                                           *"
-echo "****************************************************************"
+echo "*****************************************************************"
+echo "*  zsv build configuration                                      *"
+echo "*****************************************************************"
 
 if [ "$JQ_PREFIX" != "" ]; then
-    echo "*  - jq-prefix: $JQ_PREFIX                                     *"
+    printf '%-64s*\n' "*  - jq-prefix: $JQ_PREFIX"
 fi
 
 if [ "$PCRE2_8_PREFIX" != "" ] && [ "$HAVE_PCRE2_8" == "1" ]; then
-    echo "*  - pcre2-8-prefix: $PCRE2_8_PREFIX                                *"
+    printf '%-64s*\n' "*  - pcre2-8-prefix: $PCRE2_8_PREFIX"
 else
-    echo "*  - pcre2-8 -> NOT FOUND                                      *"
-    echo "       select and sheet regex features will not be built       *"
+    printf '%-64s*\n' "*  - pcre2-8 -> NOT FOUND"
+    printf '%-64s*\n' "       select and sheet regex features will not be built"
 fi
 
 if [ "$LDFLAGS_TERMCAP" = "" ]; then
-    echo "*  - termcap: no. \`pretty\` will use default width assumption   *"
+    printf '%-64s*\n' "*  - termcap: no. \`pretty\` will use default width assumption"
 else
-    echo "*  - termcap: yes                                              *"
+    printf '%-64s*\n' "*  - termcap: yes"
 fi
 
 if [ "$BUILD_SHAREDLIB" = "1" ]; then
-    echo "*  - build shared library: yes                                 *"
+    printf '%-64s*\n' "*  - build shared library: yes"
 else
-    echo "*  - build shared library: no                                  *"
+    printf '%-64s*\n' "*  - build shared library: no"
 fi
 
 if [ "$ZSVSHEET_BUILD" = "1" ]; then
-    echo "*  - build sheet feature: yes                                  *"
+    printf '%-64s*\n' "*  - build sheet feature: yes"
     if [ "$NCLIB" = "ncurses" ]; then
-        echo "*    ncurses library:     ncurses                              *"
+        printf '%-64s*\n' "*    ncurses library:     ncurses"
     elif [ "$NCLIB" = "ncursesw" ]; then
-        echo "*    ncurses library:     ncursesw                             *"
+        printf '%-64s*\n' "*    ncurses library:     ncursesw"
     fi
 else
-    echo "*  - build sheet feature: no                                   *"
+    printf '%-64s*\n' "*  - build sheet feature: no"
 fi
 
 if [ "$HAVE_AVX512" = "1" ]; then
-    echo "*  - using 512-bit AVX instruction set                         *"
+    printf '%-64s*\n' "*  - using 512-bit AVX instruction set"
 elif [ "$CFLAGS_AVX" = "-mavx2" ]; then
-    echo "*  - using 256-bit AVX2 instruction set                        *"
+    printf '%-64s*\n' "*  - using 256-bit AVX2 instruction set"
 elif [ "$CFLAGS_AVX" = "-mavx" ]; then
-    echo "*  - using 128-bit + AVX instruction set                       *"
+    printf '%-64s*\n' "*  - using 128-bit + AVX instruction set"
 else
-    echo "*  - using 128-bit vector size, no AVX                         *"
+    printf '%-64s*\n' "*  - using 128-bit vector size, no AVX"
 fi
 
-echo "****************************************************************"
+echo "*****************************************************************"
 
 if ! [ "$MAKE" = "" ]; then
     echo
