[MinGW] Use PDCurses instead of Ncurses
Signed-off-by: Azeem Sajid <azeem.sajid@gmail.com>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -602,15 +602,23 @@ if [ "$TRY_SHEET" != "no" ]; then
             CFLAGS_NCURSES="$CFLAGS_NCURSES -DHAVE_NCURSES"
         fi
     fi
-    ZSVSHEET_BUILD=1
-
-    if [ "$TRY_SHEET" = "yes" ] ; then
-        echo "Error: could not find either ncurses or ncursesw library; cannot build 'sheet' feature"
-        exit 1
+    if tryldflag LDFLAGS_PDCURSES -lpdcurses -L"$PREFIX"/lib ; then
+        NCLIB=pdcurses
+        LDFLAGS_NCURSES=-lpdcurses
+        if [ "$NCURSES_DYNAMIC" = "" ] ; then
+            CFLAGS_NCURSES="$CFLAGS_NCURSES -DHAVE_PDCURSES -DPDCURSES_STATIC"
+        else
+            CFLAGS_NCURSES="$CFLAGS_NCURSES -DHAVE_PDCURSES"
+        fi
     fi
+
+    ZSVSHEET_BUILD=1
     if [ "$LDFLAGS_NCURSES" = "" ] ; then
-        echo "WARNING: could not find either ncurses or ncursesw library; cannot build 'sheet' feature"
         ZSVSHEET_BUILD=0
+        echo "WARNING: could not find either ncurses or ncursesw library; cannot build 'sheet' feature"
+        if [ "$TRY_SHEET" = "yes" ] ; then
+            exit 1
+        fi
     fi
 fi
 
@@ -986,6 +994,8 @@ if [ "$ZSVSHEET_BUILD" = "1" ]; then
         printf '%-64s*\n' "*    ncurses library:     ncurses"
     elif [ "$NCLIB" = "ncursesw" ]; then
         printf '%-64s*\n' "*    ncurses library:     ncursesw"
+    elif [ "$NCLIB" = "pdcurses" ]; then
+        printf '%-64s*\n' "*    ncurses library:     pdcurses"
     fi
 else
     printf '%-64s*\n' "*  - build sheet feature: no"
